"""empty message

Revision ID: b0a47904a0aa
Revises: 434d42573d03
Create Date: 2024-09-05 14:38:58.552954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0a47904a0aa'
down_revision = '434d42573d03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fragrances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fragrances', schema=None) as batch_op:
        batch_op.drop_column('img_url')

    # ### end Alembic commands ###
